services:

  postgres:
    image: postgres:16
    container_name: ollama_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ollama
      POSTGRES_USER: ollama
      POSTGRES_PASSWORD: ollama
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ollama -d ollama"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7
    container_name: ollama_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

	  app:
	    build:
	      context: .
	      dockerfile: Dockerfile
	    container_name: ollama_backend
	    restart: unless-stopped
	    depends_on:
	      postgres:
	        condition: service_healthy
	      mongodb:
	        condition: service_started
	      ollama:
	        condition: service_started
	    environment:
	      SPRING_PROFILES_ACTIVE: prod

	      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ollama
	      SPRING_DATASOURCE_USERNAME: ollama
	      SPRING_DATASOURCE_PASSWORD: ollama

	      MONGO_HOST: mongodb
	      MONGO_DB: mongo_db

	      OLLAMA_BASE_URL: http://ollama:11434

	    ports:
	      - "8080:8080"


volumes:
  postgres_data:
  mongo_data:
  ollama_data:
