spring.application.name=ollama-agentic-ai-orchestrator
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ollama?sslmode=disable
spring.datasource.username=ollama
spring.datasource.password=ollama
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true


tool.automation.n8n-base-url=http://localhost:5678
